### ISSUE TITLE
Liste des sites grévistes

### ISSUE THREAD

**Issue by mehdichaouch** [thibault/strike-js#2]
Je suppose que si cet addons existe, il est utilisé par certains sites, donc ajouter une liste des sites en grèves au README.md ou dans un STRIKE.md permettrait de montrer le soutien ?

Pour le moment, j'ai simplement vu une sensibilisation sur loom.fr, et vous ?

**Comment by thibault** [comment]
Hello @mehdichaouch. Je te remercie pour ta suggestion. Toutefois, ce dépôt n'a pas pour vocation à référencer des sites grevistes, et utiliser cette mini-lib relève d'une initiative personnelle. Par ailleurs, je n'ai pas les ressources pour maintenir une telle liste à jour.

Je te remercie d'avoir pris le temps de suggérer cette amélioration.
