### ISSUE TITLE
Ajout d'un lien vers strike-js?

### ISSUE THREAD

**Issue by einenlum** [thibault/strike-js#3]
Bonjour ! Merci pour ce super outil !
Je note qu'il n'y a aucun lien vers strike-js lorsqu'il s'affiche. Est-ce qu'on ajouterait quelque chose comme "Powered by strike-js" en bas, même assez discret, pour que les gens qui voient l'initiative sachent comment s'y joindre ?

**Comment by thibault** [comment]
@Einenlum Hello. Merci pour la suggestion. En fait, plusieurs personnes m'ont soumis la même idée via divers caneaux. Ce n'est effectivement pas une mauvaise idée. J'y réfléchis pour une mise à jour future.

**Comment by thibault** [comment]
@Einenlum J'ai ajouté la possibilité d'intégrer des liens sur la page, et complété le README en conséquence.

Toutefois, je préfère laisser à l'initiative individuelle le choix des liens affichés.

**Comment by einenlum** [comment]
Merci beaucoup!
